[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file=["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "tools"
version = "26.0.0"
description = "Arras Energy tools for GridLAB-D"
authors = [
    {name = "David P. Chassin <dchassin@eudoxys.com>"},
    ]
maintainers = [
    {name = "David P. Chassin <dchassin@eudoxys.com>"},
    ]
readme = "README.md"
keywords = ["github","python","arras","tools","gridlabd"]
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries",
    ]
dynamic=["dependencies"]

[project.urls]
Homepage = "https://github.com/arras-energy/tools"
Documentation = "https://arras.energy/tools"
Repository = "https://github.com/arras-energy/tools.git"
Issues = "https://github.com/arras-energy/tools/issues"

